ZCS-3326: Delegated admin cannot download the result of account migration CSV file
Zimbra/zm-bulkprovision-admin-zimlet pull request #7
Opened 2017-12-18 01:43 UTC by k-kato

The following Pull Request changes REST API of importing accounts and downloading search results.
https://github.com/Zimbra/zm-bulkprovision-store/pull/1

This zimlet (UI code) needs to use new APIs.
- Regarding bulk provisioning (imporing accounts), "action" param is removed as follows:
(current API) /service/extension/com_zimbra_bulkprovision/bulkdownload?action=getBulkFile&fileID=xxxx&fileFormat=xxxx
(new API)     /service/extension/com_zimbra_bulkprovision/bulkdownload?fileID=xxxx&fileFormat=xxxx

- Regarding downloading search results, "action" param is removed and path is changed as follows:
(current API) /service/extension/com_zimbra_bulkprovision/bulkdownload?action=getSR&query=xxxx
(new API)     /service/extension/com_zimbra_bulkprovision/search_results_download?query=xxxx

2017-12-18 01:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-bulkprovision-admin-zimlet?pullRequest=7) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-bulkprovision-admin-zimlet?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-bulkprovision-admin-zimlet?pullRequest=7) it.</sub>

2017-12-28 11:41 UTC, silentsakky approved these changes

2018-01-08 14:03 UTC, fatkudu requested changes
Please can you include the GitHub description you have here in the commit comment text - it is more useful there in the long term.

2018-01-10 11:17 UTC, grishick approved these changes

2018-01-11 02:41 UTC, k-kato commented
@fatkudu I modified the commit comment.

2018-01-11 12:32 UTC, fatkudu approved these changes
Great.  Thanks for that.

2018-07-19 19:04 UTC, merged